### ISSUE TITLE
How to choose range Z of BEV boundary ?

### ISSUE THREAD

**Issue by SofianeB-03** [hyungikim4/SFA3D#2]
Hello @hyungikim4 , thank you to share your code! You said "range Z is dependant of the height of lidar sensor". Can you explain it please and so how to choose the range Z for Waymo dataset for example ?

Thanks again.

**Comment by hyungikim4** [comment]
It means that the z-axis range is dependent on the Lidar mount position and vertical FOV. Since the maximum and minimum values of x, y, and z are used to create a bird's eye view image (input of network), I set the z value of the ground obtained from the Lidar point cloud to 'minZ', and set 'maxZ' to 'minZ+4.0'. After visualizing the Lidar data from the Waymo data set, you can get the z-value of the ground and use it to set 'minZ' and 'maxZ'.

**Comment by SofianeB-03** [comment]
Thank you for your explanation !
